In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/marine_engine_fault_dataset (1).csv')
data.head()

,Timestamp,Shaft_RPM,Engine_Load,Fuel_Flow,Air_Pressure,Ambient_Temp,Oil_Temp,Oil_Pressure,Vibration_X,Vibration_Y,Vibration_Z,Fault_Label,Cylinder1_Pressure,Cylinder1_Exhaust_Temp,Cylinder2_Pressure,Cylinder2_Exhaust_Temp,Cylinder3_Pressure,Cylinder3_Exhaust_Temp,Cylinder4_Pressure,Cylinder4_Exhaust_Temp
0,2024-01-01 00:00:00,965.414073,72.397307,114.665107,1.025896,27.055404,73.000474,3.407503,0.087248,0.076305,0.069988,0,157.710104,418.761079,139.335694,449.428109,151.140472,400.142839,138.194303,469.788241
1,2024-01-01 00:00:01,996.888052,90.818713,156.425262,1.258291,26.686902,77.039208,2.935203,0.035802,0.066677,0.077774,0,163.301036,416.912327,151.742643,383.042000,147.326823,400.557809,131.104323,430.206873
2,2024-01-01 00:00:02,948.424675,76.358257,126.188656,1.184234,25.482428,79.076912,3.942825,0.102402,0.047158,0.046104,0,148.868866,455.707882,155.441964,374.099103,131.471313,455.522306,143.895843,417.453433
3,2024-01-01 00:00:03,982.370968,63.822324,107.840402,1.150488,24.372997,78.028895,3.893302,0.065176,0.067617,0.041622,0,142.861369,464.990838,137.514280,407.003480,154.426397,423.237676,145.149830,383.834081
4,2024-01-01 00:00:04,973.166374,69.483056,113.637069,1.174918,30.678317,78.353818,3.518891,0.047297,0.085649,0.093252,0,138.080575,407.992398,144.795201,482.424962,152.438065,427.269295,162.077661,450.501985

In [10]:
data.isnull().sum()
data = data.dropna()
data
data = data.drop_duplicates()
data

,Timestamp,Shaft_RPM,Engine_Load,Fuel_Flow,Air_Pressure,Ambient_Temp,Oil_Temp,Oil_Pressure,Vibration_X,Vibration_Y,Vibration_Z,Fault_Label,Cylinder1_Pressure,Cylinder1_Exhaust_Temp,Cylinder2_Pressure,Cylinder2_Exhaust_Temp,Cylinder3_Pressure,Cylinder3_Exhaust_Temp,Cylinder4_Pressure,Cylinder4_Exhaust_Temp
0,2024-01-01 00:00:00,965.414073,72.397307,114.665107,1.025896,27.055404,73.000474,3.407503,0.087248,0.076305,0.069988,0,157.710104,418.761079,139.335694,449.428109,151.140472,400.142839,138.194303,469.788241
1,2024-01-01 00:00:01,996.888052,90.818713,156.425262,1.258291,26.686902,77.039208,2.935203,0.035802,0.066677,0.077774,0,163.301036,416.912327,151.742643,383.042000,147.326823,400.557809,131.104323,430.206873
2,2024-01-01 00:00:02,948.424675,76.358257,126.188656,1.184234,25.482428,79.076912,3.942825,0.102402,0.047158,0.046104,0,148.868866,455.707882,155.441964,374.099103,131.471313,455.522306,143.895843,417.453433
3,2024-01-01 00:00:03,982.370968,63.822324,107.840402,1.150488,24.372997,78.028895,3.893302,0.065176,0.067617,0.041622,0,142.861369,464.990838,137.514280,407.003480,154.426397,423.237676,145.149830,383.834081
4,2024-01-01 00:00:04,973.166374,69.483056,113.637069,1.174918,30.678317,78.353818,3.518891,0.047297,0.085649,0.093252,0,138.080575,407.992398,144.795201,482.424962,152.438065,427.269295,162.077661,450.501985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2024-01-01 02:46:35,927.425457,87.725739,111.499731,1.113578,22.750387,80.476350,3.405024,0.060880,0.038950,0.083647,0,156.744246,433.514089,131.863489,385.564915,142.939393,488.531652,160.730329,429.839846
9996,2024-01-01 02:46:36,996.372362,64.716126,143.344425,1.188479,27.202907,81.488747,3.746873,0.068109,0.038700,0.021936,0,127.299007,449.949988,154.616035,428.006118,138.444477,438.231183,153.707112,450.274664
9997,2024-01-01 02:46:37,921.728914,34.614266,114.287530,1.187564,23.849295,82.763312,3.349990,0.054361,0.066472,0.064506,0,165.110101,415.394811,170.056102,471.034358,148.002473,432.060190,128.142606,413.039316
9998,2024-01-01 02:46:38,940.193390,75.633493,159.528062,1.178307,27.049806,81.636159,2.754986,0.038497,0.075067,0.061815,0,154.966481,424.032166,148.744202,385.815896,133.609915,433.157294,141.792309,382.778918
9999,2024-01-01 02:46:39,963.846229,71.444945,141.138450,1.065738,31.385956,80.273322,3.012553,0.058376,0.050167,0.088747,0,147.582393,387.016775,137.177686,360.048941,149.848392,433.975209,154.095358,439.516794

In [12]:
x = data.drop(data.columns[11], axis=1).values

y = data.iloc[:,11].values

In [13]:
print(x)
print(y)

[['2024-01-01 00:00:00' 965.4140726802144 72.39730688423849 ...
  400.1428388267937 138.19430254740075 469.7882410713132]
 ['2024-01-01 00:00:01' 996.8880520879256 90.81871276917543 ...
  400.557808511954 131.10432307531437 430.20687303491377]
 ['2024-01-01 00:00:02' 948.4246746121972 76.35825740705137 ...
  455.5223061688783 143.89584259034743 417.4534329813856]
 ...
 ['2024-01-01 02:46:37' 921.7289143251588 34.61426604035569 ...
  432.060189951417 128.14260624410693 413.0393161930157]
 ['2024-01-01 02:46:38' 940.1933900886902 75.63349315006228 ...
  433.15729361963696 141.79230890875328 382.7789183762849]
 ['2024-01-01 02:46:39' 963.846228628674 71.4449449568007 ...
  433.9752086766964 154.09535790617622 439.5167943343973]]
[0 0 0 ... 0 0 0]

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [17]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
from sklearn.linear_model import LogisticRegression

classification = LogisticRegression(max_iter=1000)

classification.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [19]:
y_pred = classification.predict(x_test)

print(y_pred)

[0 0 0 ... 0 0 5]

In [20]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

Accuracy : 0.8525

In [21]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[1273   10   11    8    0    2    3    0]
 [  99    6    2    1    0    0    0    0]
 [  83    0   16    0    0    0    0    0]
 [  64    0    2   21    0    1    0    0]
 [   0    0    0    0  107    0    0    0]
 [   5    0    0    0    0   89    0    0]
 [   3    0    0    0    0    0   95    0]
 [   0    0    0    0    0    1    0   98]]

In [22]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.97      0.90      1307
           1       0.38      0.06      0.10       108
           2       0.52      0.16      0.25        99
           3       0.70      0.24      0.36        88
           4       1.00      1.00      1.00       107
           5       0.96      0.95      0.95        94
           6       0.97      0.97      0.97        98
           7       1.00      0.99      0.99        99

    accuracy                           0.85      2000
   macro avg       0.79      0.67      0.69      2000
weighted avg       0.82      0.85      0.82      2000

In [23]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.60.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.51)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow<25,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.51.0)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.24.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.60.0-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 64.4 MB/s eta 0:00:00
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 72.9 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.3 streamlit-1.60.0

In [29]:
import pickle

pickle.dump(classification, open("logistic_model.pkl","wb"))


print("Model saved successfully")

Model saved successfully

In [30]:
%%writefile app.py

import streamlit as st

st.title("Marine Engine Fault Prediction")

st.write("My Streamlit App is Running")

Overwriting app.py

In [32]:
!streamlit run app.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-07-25 12:12:09.625 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.125.21.130:8501

  Stopping...
  Stopping...
  Stopping...
  Stopping...

In [34]:
%%writefile requirements.txt

streamlit
numpy
pandas
scikit-learn

Writing requirements.txt